[package]
name = "github_issues_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
diesel = { version = "2.1", features = ["sqlite"] }

[dev-dependencies]

